services:
  backend:
    build: ./backend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb

  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   container_name: db
  #   volumes:
  #     - dbdata:/var/lib/postgresql/data/
  pgdb:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/src
    depends_on:
      - backend

volumes:
  postgres_data:
